---
sudo: false

language: java

jdk: oraclejdk8

before_cache:
  - rm --force --recursive --verbose $HOME/.m2/repository/com/github/gantsign

cache:
  directories:
    - $HOME/.m2

install: true
script:
  - ./mvnw clean install

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
